import {
  CleaningIcon,
  FurnitureIcon,
  HandymanIcon,
  HeavyIcon,
  MovingIcon,
  PaintingIcon,
} from "Src/Assets/index";

export const ServicesTypes = [
  {
    id: 1,
    name: "Furniture assembly",
    details: "I want to assemble my material",
    icon: <FurnitureIcon />,
    header: "Choose what you would like to assemble",
    questions: [
      "Furniture assembly",
      "Home assembly",
      "Bookshelf assembly",
      "Office assembly",
      "Crib assembly",
      "Desk assembly",
    ],
  },
  {
    id: 2,
    name: "Cleaning",
    details: "I want to clean my space",
    icon: <CleaningIcon />,
    header: "Choose what you would like to clean",
    questions: [
      "Office cleaning",
      "Thorough Cleaning",
      "Germ-Killing Services",
      "Cleaning for Moving In",
      "Cleaning for Vacation Homes",
      "Carpets Cleaning",
      "Car Washing ",
      "Laundry help",
      "High-Pressure Cleaning",
      "High-Pressure Cleaning",
    ],
  },
  {
    id: 3,
    name: "Painting",
    details: "I want to paint my space",
    icon: <PaintingIcon />,
    header: "Choose what you would like to paint",
    questions: [" House painting", "Office painting"],
  },
  {
    id: 4,
    name: "Handyman",
    details: "I need handyman services",
    icon: <HandymanIcon />,
    header: "Choose what you would like taskwalker to handle around the home",
    questions: [
      "Fixing Doors, Cabinets, & Furniture",
      "Installing and Fixing Appliances",
      "Putting Together Furniture",
      "Attaching TVs to Walls",
      "Helping with Floors and Tiles",
      "Handling Plumbing Problems",
      "Painting Walls",
      "Keeping Homes in Good Shape",
      "Putting Up Lights",
      "Installing Cabinets",
      "Putting in Doorbells",
      "Hanging Pictures and frames",
      "Hanging Curtains and Blinds",
      "Installing Air Conditioners",
      "Carpentry Jobs",
      "Putting in Doorbells",
      "Sorting Out Electrical Issues",
    ],
  },
  {
    id: 5,
    name: "Moving",
    details: "I need help moving",
    icon: <MovingIcon />,
    header: "Choose what you would like move",
    questions: [
      "Packing Assistance",
      "Relocating Storage Units",
      "Moving Furniture",
      "Removing Couches",
      "Removing Appliances",
      "Rearranging Furniture",
      "Moving Furniture Within Homes",
      "Removing Junk",
      "Unpacking Help",
    ],
  },
  {
    id: 6,
    name: "Heavy lifting",
    details: "I need help with heavy lifting",
    icon: <HeavyIcon />,
    header: "Choose the heavy materials you would like lift",
    questions: [
      "Gym equipment",
      "Safe and vaults",
      "Machinery or industrial equipment",
      "Construction materials",
      "Removing Appliances",
      "Rearranging Furniture",
      "Moving Furniture Within Homes",
      "Removing Junk",
      "Unpacking Help",
    ],
  },
];
