import Head from "next/head";
import { Inter } from "next/font/google";
import { Onboarding } from "@/container/Onboarding";
import { Page } from "@/container/Onboarding/Home";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <style jsx>
          {`
            body {
              min-height: calc(100% + env(safe-area-inset-top));
              padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);
            }
          `}
        </style>
      </Head>
      <Onboarding />
    </>
  );
}
