import Head from "next/head";
import { Inter } from "next/font/google";
import { Onboarding } from "@/container/Onboarding";
import { Page } from "@/container/Onboarding/Home";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <meta name="theme-color" content="#111111" />
        <link rel="stylesheet" href="https://unpkg.com/@material/toolbar@0.4.11/dist/mdc.toolbar.min.css" />
        <link rel="stylesheet" href="https://unpkg.com/@material/elevation@0.1.13/dist/mdc.elevation.min.css" />
      </Head>
      <Onboarding />
    </>
  );
}
